/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sparkjava;

import spark.Spark;
import java.util.ArrayList;


final class User {

    private String firstName;
    private String lastName;
    private String email;
    private int vote = 0;

public User(String firstName, String lastName, String email, int vote){
    this.firstName = firstName;
    this.lastName = lastName;
    this.email = email;
    this.vote = vote;
}

public String getName(){
    return firstName + " " + lastName;
}

public int getVote(){
    return vote;
}

public void vote(){
    vote++;
}
}

public class App {

    static ArrayList<User> users = new ArrayList<User>();

    public static void main(String[] args) {

        users.add(new User("Tom", "Meier", "Tom.Meier@hotmail.com", 0));
        users.add(new User("Luna", "Müller", "Luna.Mueller@hotmail.com", 0));
        users.add(new User("Hans", "Frey", "Hans.Frey@hotmail.com", 0));


        Spark.get("/users/:id/welcome", (req, res) -> {
            String idString = req.params("id");
            int id = Integer.parseInt(idString);
            String name = users.get(id).getName() + " | Dein Votingergebnis ist: " + users.get(id).getVote();
            return "Hallo " + name; });

        Spark.put("/users/:id/vote", (req, res) -> {
            String idString = req.params("id");
            int id = Integer.parseInt(idString);
            users.get(id).vote();
            return "ok";});
                
    }
}
